### ISSUE TITLE
window.open 不能全屏打开窗口

### ISSUE THREAD

**Issue by mingMor** [michaelwasserman/window-placement-demo#10]

**Comment by michaelwasserman** [comment]
Thanks for filing this issue: "Can't open window in full screen". Unfortunately [Chromium is no longer pursuing that feature](https://chromestatus.com/feature/6002307972464640), after the [Origin Trial](https://developer.chrome.com/origintrials/#/view_trial/106960491150049281) ended without solid developer alignment.

See Chromium's newer [Automatic Fullscreen Content Setting](https://chromestatus.com/feature/6218822004768768), the [Explainer](https://github.com/explainers-by-googlers/html-fullscreen-without-a-gesture), and my [iwa-windowing-example](https://github.com/michaelwasserman/iwa-windowing-example). Please give feedback and use cases in the Explainer repo or in W3C and WHATWG venues.

I'll remove this demo's fullscreen checkbox soon, and may eventually re-add something similar.

**Comment by michaelwasserman** [comment]
Closing per [commit](https://github.com/michaelwasserman/window-placement-demo/commit/ddb6974abe1329de7f01e8806252c7d07faae89e)
