### ISSUE TITLE
The window-placement working on localhost but not working on the non-localhost site

### ISSUE THREAD

**Issue by huy1912** [michaelwasserman/window-placement-demo#3]
I've tried with the demo. It's working perfectly fine on the localhost.
It's not working on the non-localhost host environment with the below error

<img width="1187" alt="Screenshot 2021-10-06 at 12 05 00 AM" src="https://user-images.githubusercontent.com/2849751/136060790-a6b7cee2-a41f-4e82-8984-52262c1b5100.png">

I found out that the below check with the given screen
```js
if (!('getScreens' in self) || !('isExtended' in screen) || !('onchange' in screen)) {
      showWarning("Please use Chrome 93+ to demo new multi-screen features");
}
```

Do you have any solution to make it work in the non-localhost environment?

Thanks,
Huy

**Comment by huy1912** [comment]
It's my bad without registering the host via https://developer.chrome.com/origintrials/#/registration.
It's working fine after updating the origin token.

Thanks

**Comment by michaelwasserman** [comment]
I'm glad you found the answer yourself, thanks for trying the API and my demo!
